import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import LeftSideBar from "@/components/layout/LeftSideBar";
import RightSideBar from "@/components/layout/RightSideBar";
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import BottomBar from "@/components/layout/BottomBar";
import { fetchUser } from "@/actions/user.actions";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { getUser } = getKindeServerSession();
  const currentUser = await getUser();
  const user = await fetchUser(currentUser?.id);
  return (
    <html suppressHydrationWarning={true} lang="en">
      <body className={`${poppins.className} bg-black text-white `}>
        <ToastContainer
          position="bottom-right"
          autoClose={2000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          theme="dark"
        />
        <main className="flex  justify-center items-center">
          <LeftSideBar user={user!} />
          <section className="w-[648px] relative border-x border-[#2f3336]  min-h-screen ">
            <div className="w-full px-4  max-w-4xl">{children}</div>
            <BottomBar user={user!} />
          </section>
          <RightSideBar />
        </main>
      </body>
    </html>
  );
}
